call deploy.bat ProfilesActiveCampaign Test
call deploy.bat ProfilesActiveCampaignUpdate Test
call deploy.bat ProfilesActiveNotifications Test
call deploy.bat ProfilesActiveNotificationsCount Test
call deploy.bat ProfilesAuthorizer Test
call deploy.bat ProfilesCancelPayment Test
call deploy.bat ProfilesChangePassword Test
call deploy.bat ProfilesChangePasswordByEmail Test
call deploy.bat ProfilesChargebeeWebhook Test
call deploy.bat ProfilesCheckoutHostedPage Test
call deploy.bat ProfilesDeleteAccount Test
call deploy.bat ProfilesDeleteActiveCampaignContact Test
call deploy.bat ProfilesDeleteEmail Test
call deploy.bat ProfilesDeletePicture Test
call deploy.bat ProfilesDeleteUselessUsers Test
call deploy.bat ProfilesDeleteUsersS3Objects Test
call deploy.bat ProfilesFacebookConnect Test
call deploy.bat ProfilesFacebookDisconnect Test
call deploy.bat ProfilesFacebookScrapeImage Test
call deploy.bat ProfilesFacebookSignIn Test
call deploy.bat ProfilesFacebookSignInAsync Test
call deploy.bat ProfilesFacebookSignUp Test
call deploy.bat ProfilesFacebookSignUpAsync Test
call deploy.bat ProfilesGenerateInterpersonalReport Test
call deploy.bat ProfilesGenerateUserGuidesReport Test
call deploy.bat ProfilesGenerateUserPartnerReport Test
call deploy.bat ProfilesGenerateUserProfileReport Test
call deploy.bat ProfilesGenericProfileImage Test
call deploy.bat ProfilesGenericSimilarityImage Test
call deploy.bat ProfilesGetBig5 Test
call deploy.bat ProfilesGetDescriptions Test
call deploy.bat ProfilesGetInvoiceUrl Test
call deploy.bat ProfilesGetLanguage Test
call deploy.bat ProfilesGetPrivacySettings Test
call deploy.bat ProfilesGetProducts Test
call deploy.bat ProfilesGetPurchasedProductDetails Test
call deploy.bat ProfilesGetSettingsBillingInfo Test
call deploy.bat ProfilesGetUserBasicInfo Test
call deploy.bat ProfilesGetUserProfile Test
call deploy.bat ProfilesInterpersonal Test
call deploy.bat ProfilesLambdaWarmer Test
call deploy.bat ProfilesMakeProductPayment Test
call deploy_edge.bat ProfilesMetatagEdge Test
call deploy.bat ProfilesMystery Test
call deploy.bat ProfilesMysteryButton Test
call deploy.bat ProfilesNotifications Test
call deploy.bat ProfilesPostAnswers Test
call deploy.bat ProfilesProductSalesDetails Test
call deploy.bat ProfilesRegenerateFacebookImages Test
call deploy.bat ProfilesScrapeInterpersonalSharedUrl Test
call deploy.bat ProfilesSendNotificationsToFriendsAsync Test
call deploy.bat ProfilesSendPasswordResetLink Test
call deploy.bat ProfilesSignIn Test
call deploy.bat ProfilesSignUp Test
call deploy.bat ProfilesTermsAndConditionCheck Test
call deploy.bat ProfilesTestLoginInterface Test
call deploy.bat ProfilesUpdateCoachingGotit Test
call deploy.bat ProfilesUpdateConsent Test
call deploy.bat ProfilesUpdateFacebookDetailsAsync Test
call deploy.bat ProfilesUpdatePrimaryEmail Test
call deploy.bat ProfilesUpdatePrivacySettings Test
call deploy.bat ProfilesUpdateUserBasicInfo Test
call deploy.bat ProfilesUpdateUsersAnswers Test
call deploy.bat ProfilesUploadPicture Test
call deploy.bat ProfilesUserDetailsFacebookConnect Test
call deploy.bat ProfilesUserFriendsList Test
call deploy.bat ProfilesUserPartnerSearch Test
call deploy.bat ProfilesUserRegenerateFacebookImages Test
call deploy.bat ProfilesValidateLink Test
call deploy.bat ProfilesHealthCheck Test
call deploy.bat ProfilesGetDataForEdge Test
